<?php
/**
 * Created by PhpStorm.
 * User: lelouch
 * Date: 19/6/16
 * Time: 9:35 AM
 */

$Directory = new RecursiveDirectoryIterator(__DIR__ . '/../src/');
$Iterator = new RecursiveIteratorIterator($Directory);
$Regex = new RegexIterator($Iterator, '/^.+\.php$/i', RecursiveRegexIterator::GET_MATCH);

$autoload = <<<AUTOLOAD
<?php
/*
 * Autoload file, automagically generated.
 * Do not edit this file, unless, you know what you are doing!
 */

AUTOLOAD;

foreach ($Regex as $file) {
    $file = $file[0];
    $fileName = end(explode("/", $file));
    if($fileName !== "Client.php" || !strpos($file, "twig.cache")) {
        $autoload .= "require_once '" . $file . "';\n";
    }
}

file_put_contents(__DIR__ . "/../autoloads/autoloader.php", $autoload);